name: release
on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages 
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: "main"

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.10.13

    - name: Install dependencies
      run: |
        sudo apt-get install python3-sphinx python3-sphinx-rtd-theme
    - name: Build pages
      run: |
        make html
        touch docs/.nojekyll
    - name: Deploy
      uses: actions/deploy-pages@v1
